### ISSUE TITLE
fatal: not a git repository

### ISSUE THREAD

**Issue by mitchdetailed** [rusoku/TouCAN-SocketCAN_DKMS#1]
Command :~ git archive --prefix=toucan-1.0/ -o toucan-1.0.tar HEAD
returns :~ fatal: not a git repository (or any of the parent directories): .git

**Comment by rusoku** [comment]
git clone https://github.com/rusoku/TouCAN-SocketCAN_DKMS

**Comment by rusoku** [comment]
git clone https://github.com/rusoku/TouCAN-SocketCAN_DKMS
